### ISSUE TITLE
Question about one serial connection

### ISSUE THREAD

**Issue by JCrew7384** [InitialState/fona-pi-zero#3]
Hi.

This is the first time I've seen a reference to the Fona only being able to send GPS data OR PPP data, but not both, through serial. Is this a restriction of Pi Zero? Other tutorials don't bring this up (e.g. https://learn.adafruit.com/adafruit-io-basics-gps/arduino-code) implies that the GPS can be sent to Adafruit IO remotely as well...

Thoughts?

**Comment by RChloe** [comment]
This is _kind of_ of a Raspberry Pi restriction. The Pi only allows you to make one serial connection at a time. PPPD is a very reliable way to handle the cellular connection, however, that's all that it does. You can't add reading from the GPS to it. You _can_ handle the cellular connection yourself, but that get's complicated and you'd basically have to reconstruct what PPPD does in your script, but then you could also read from the GPS at the same time.

The tutorials that don't mention that are powered by an Arduino (which can't run the PPPD service). You'll notice they handle the cellular connection manually inside of the sketch. It is much easier to handle serial connections on Arduino just because the board itself is controlled through a serial connection.

The script in this tutorial just collects the GPS data and then streams it over the cellular connection. It's effectively accomplishing exactly what having both connections open at the same time would. It doesn't have to be buffered either - I found that PPPD could handle rapidly turning on and off the cellular connection no problem.

Just a teensy clarification - it isn't that you can't _send_ GPS data and PPP data at the same time. It's that you can't _read_ GPS data while the PPP connection is open.

Hope that helps!

**Comment by JCrew7384** [comment]
When handling the PPP connection through serial, I also lose the ability to interact with the Fona via the screen command. So when PPP is active, all I can do is data connection, no calls, no, sms, etc. once PPP is turned off, all of that can resume?

**Comment by RChloe** [comment]
I believe so.
